/**
 *
 * @author apin9
 */
public class Item_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Item_MainMenu
     */
    public Item_MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JLabel();
        HelpButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        Item_BarangButton = new javax.swing.JButton();
        lbBackgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenu.setFont(new java.awt.Font("Mistral", 0, 36)); // NOI18N
        MainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenu.setText("~ Main Menu ~");
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 422, 45));

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 420, -1));

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 420, -1));

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 420, -1));

        Item_BarangButton.setText("Lihat Barang Elektronik");
        Item_BarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_BarangButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Item_BarangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, -1));

        lbBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-648446306-1024x1024.jpg"))); // NOI18N
        lbBackgroud.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbBackgroudPropertyChange(evt);
            }
        });
        getContentPane().add(lbBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            new Item_Help().setVisible(true);
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void Item_BarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_BarangButtonActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            new Item_DaftarElektronik().setVisible(true);
    }//GEN-LAST:event_Item_BarangButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            new Item_LoginPage().setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void lbBackgroudPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbBackgroudPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBackgroudPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item_MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton Item_BarangButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel MainMenu;
    private javax.swing.JLabel lbBackgroud;
    // End of variables declaration//GEN-END:variables
}
